# -*- coding: utf-8 -*-
"""my_peragaru.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOLQxrtLBYJcvrwCReanplA_mXdTrcaZ
"""

!pip install streamlit
import streamlit as st
import yfinance as yf
import pandas as pd

# 1. アプリのタイトルを表示
st.title('俺のPERAGARU (ベータ版)')

# 2. ユーザーが銘柄コードを入力する場所を作る
# デフォルトはトヨタ(7203)にしています。.Tは東証の意味です。
ticker = st.text_input('銘柄コードを入力してください (例: 7203.T)', '7203.T')

# 3. 期間を選ぶスライダーを作る
days = st.slider('表示する期間（日数）', 30, 365, 180)

# 4. ボタンが押されたらデータを取得して表示
if st.button('分析開始'):
    try:
        # 株価データの取得 (Yahoo Financeから)
        df = yf.download(ticker, period=f'{days}d')

        # 最新の終値を表示
        latest_price = df['Close'].iloc[-1]
        st.metric(label="現在の株価", value=f"{latest_price:.1f} 円")

        # チャートを描く（これだけでインタラクティブなグラフになります）
        st.line_chart(df['Close'])

        # データの中身（エクセルっぽい表）を表示
        st.write('詳細データ:')
        st.dataframe(df.tail())

    except Exception as e:
        st.error(f'エラーが発生しました: {e}')
        st.write('銘柄コードが正しいか確認してください（日本株は数字4桁 + .T です）')